services:
  db:
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: "no"
    env_file: ./back/.env
    image: mysql:8.0.39-bookworm
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./docker/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
  back:
    build:
      context: .
      dockerfile: "./docker/back/Dockerfile"
    restart: "no"
    env_file: ./back/.env
    volumes:
      - ./back/:/opt/app/
    ports:
      - '3000:3000'
    depends_on:
      - db
  front:
    user: "${USER_ID}"
    build:
      context: .
      dockerfile: "./docker/front/Dockerfile"
      args:
        - NODE_ENV=development
    restart: "no"
    volumes:
      - ./front/:/opt/app/
    ports:
      - '4200:4200'
    depends_on:
      - db
      - back
